---
- name: Conf db server
  hosts: DB
  become: true

  tasks:
    - name: install db
      yum:
        name:
          - postgresql16
          - postgresql16-contrib
        state: present
        update_cache: yes
    - name: init db
      raw: /etc/init.d/postgresql initdb
      ignore_errors: yes
    - name: start postgress
      service: 
        name: postgresql
        state: started
        enabled: yes
      when: inventory_hostname=='db01'

    - name: Create user
      raw: psql -c "CREATE USER testuser WITH PASSWORD 'testpassword'" -U postgres && createdb -O testuser  testdb -U postgres
      ignore_errors: yes
    - name: edit master cfg
      lineinfile:
        path: /var/lib/pgsql/data/postgresql.conf
        line: listen_addresses = '*'
    - name: master wal
      lineinfile: 
        path: /var/lib/pgsql/data/postgresql.conf
        line: wal_level = replica
    - name: copy pg_hba
      blockinfile:
        path: /var/lib/pgsql/data/pg_hba.conf
        block: |
          host		all		all		192.168.10.0/24		trust
          host    replication     postgres                192.168.10.0/24        md5
      when: inventory_hostname=='db01'
    - name: restart db
      service:
        name: postgresql
        state: restarted
        enabled: yes
      when: inventory_hostname=='db01'
    - name: edit  password
      raw: psql -c "ALTER USER postgres WITH PASSWORD 'P@ssw0rd'" -U postgres
      when: inventory_hostname=='db01'
    - name: rm data 
      file:
        path: /var/lib/pgsql/data
        state: absent 
      when: inventory_hostname=='db02'
    - name: base backup 
      raw: export PGPASSWORD='P@ssw0rd' ; pg_basebackup -U postgres -h 192.168.10.69 -D /var/lib/pgsql/data/ -R -P ; chown -R postgres:postgres /var/lib/pgsql/data
      when: inventory_hostname=='db02'
    - name: del str
      lineinfile:
        path: /var/lib/pgsql/data/pg_hba.conf
        line: ' host    replication     postgres                192.168.10.0/24        md5'
        state: absent
      when: inventory_hostname=='db02'
    - name: restart psql
      service:
        name: postgresql
        state: restarted
        enabled: yes
      when: inventory_hostname=='db02'


    

