---
- name: hap
  hosts: HA
  become: true
  tasks:
    - name: install HAPROXY
      yum: 
        name: haproxy
        state: installed
        update_cache: yes
    - name: copy cfg
      copy:
        src: /home/altlinux/bin/playbook/files/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
    - name: start HAProxy
      service:
        name: haproxy
        state: started
    - name: copy keepalived1 cfg
      copy:
        src: /home/altlinux/bin/playbook/files/keepalived01.conf
        dest: /etc/keepalived/keepalived.conf
      when: inventory_hostname=='hap01'
    - name: copy keepalived2 cfg
      copy:
        src: /home/altlinux/bin/playbook/files/keepalived02.conf
        dest: /etc/keepalived/keepalived.conf
      when: inventory_hostname=='hap02'
    - name: start keepalived
      service:
        name: haproxy
        state: started
