---
- name: tmp
  hosts: all
  become: true
  tasks:
    - name: rm tmp line in fstab
      lineinfile:
        path: /etc/fstab
        line: 'tmpfs            /tmp                    tmpfs   nosuid                          0 0'
        state: absent
    - name: add new tmp line
      lineinfile:
        path: /etc/fstab
        line: 'tmpfs            /tmp                    tmpfs   nosuid,size=2G                          0 0'
        state: present
    - name: reboot
      reboot:
